; Єдина машинна authority мовних поверхонь — numeric-only schema.
; Значення первинне. Мови рівноправні.
;
; Кожен перший атом — непрозорий semantic ID і містить ТІЛЬКИ цифри.
; uk/ukr/en/sa — людські поверхні. sym — спільна немовна нотація.
; Порядок surface-форм не має семантичного значення.
; Старий uk-sa-coverage.wsm більше НЕ є authority.

(sr/1
  (0001 (en quote stable) (uk як-є stable) (ukr як-є stable) (sa svarūpa stable) (sym ' stable))
  (0002 (en atom stable) (uk атом? stable) (ukr атом? stable) (sa aṇu stable) (sym .? stable))
  (0003 (en eq stable) (uk тотожне? stable) (ukr тотожне? stable) (sa abheda stable) (sym =? stable))
  (0004 (en cons stable) (uk сполучити stable) (ukr сполучити stable) (sa saṃyuj stable) (sym : stable))
  (0005 (en car stable) (uk перше stable) (ukr перше stable) (sa ādi stable) (sym :п stable))
  (0006 (en cdr stable) (uk решта stable) (ukr решта stable) (sa śeṣa stable) (sym :р stable))
  (0007 (en cond stable) (uk за-умовою stable) (ukr за-умовою stable) (sa anukrama stable) (sym ?: stable))
  (0010 (en lambda stable) (uk функція stable) (ukr функція stable) (sa — missing))
  (0011 (en define stable) (uk визначити stable) (ukr визначити stable) (sa — missing))
  (0012 (en defmacro stable) (uk визначити-макрос stable) (ukr визначити-макрос stable) (sa — missing) (compat defmacro-derived compatibility-only))
  (1000 (en def compatibility-only) (uk — compatibility-only) (ukr визначити candidate) (sa — compatibility-only))
  (0104 (en — missing) (uk додати stable) (ukr додати stable) (sa yoga stable) (sym + stable))
  (1001 (en — missing) (uk відняти stable) (ukr відняти stable) (sa viyoga stable) (sym - stable))
  (1002 (en — missing) (uk помножити stable) (ukr помножити stable) (sa guṇana stable) (sym * stable))
  (1003 (en — missing) (uk поділити stable) (ukr поділити stable) (sa haraṇa stable) (sym / stable))
  (1004 (en abs stable) (uk модуль stable) (ukr модуль stable) (sa rūpa candidate))
  (1005 (en min stable) (uk найменше stable) (ukr найменше stable) (sa alpatara stable))
  (1006 (en max stable) (uk найбільше stable) (ukr найбільше stable) (sa brhattara stable))
  (1007 (en mod stable) (uk остача stable) (ukr остача stable) (sa avasiṣṭa stable))
  (1008 (en quotient stable) (uk частка stable) (ukr частка stable) (sa bhāga stable))
  (1009 (en sqrt stable) (uk корінь stable) (ukr корінь stable) (sa mūla stable))
  (1010 (en isqrt stable) (uk цілий-корінь stable) (ukr цілий-корінь stable) (sa sakalamūla stable))
  (1011 (en min-list stable) (uk найменше-у-списку stable) (ukr найменше-у-списку stable) (sa — missing))
  (1012 (en max-list stable) (uk найбільше-у-списку stable) (ukr найбільше-у-списку stable) (sa — missing))
  (1013 (en largest-chunk compatibility-only) (uk — compatibility-only) (ukr найбільший-фрагмент candidate) (sa — compatibility-only))
  (1014 (en — missing) (uk менше? stable) (ukr менше? stable) (sa hīna? stable) (sym < stable))
  (1015 (en — missing) (uk більше? stable) (ukr більше? stable) (sa adhika? stable) (sym > stable))
  (1016 (en — missing) (uk рівне? stable) (ukr рівне? stable) (sa sama? stable) (sym = stable))
  (1017 (en — missing) (uk не-більше? stable) (ukr не-більше? stable) (sa na-adhika? candidate) (sym <= stable))
  (1018 (en — missing) (uk не-менше? stable) (ukr не-менше? stable) (sa na-hīna? candidate) (sym >= stable))
  (1019 (en nondecreasing-from? compatibility-only) (uk — compatibility-only) (ukr неспадне-починаючи-з? candidate) (sa — compatibility-only))
  (1020 (en nonincreasing-from? compatibility-only) (uk — compatibility-only) (ukr незростаюче-починаючи-з? candidate) (sa — compatibility-only))
  (1021 (en not stable) (uk хибне? stable) (ukr хибне? stable) (sa na stable))
  (1022 (en equal? stable) (uk однакові? stable) (ukr однакові? stable) (sa tulya? stable))
  (1023 (en symbol? stable) (uk символ? stable) (ukr символ? stable) (sa nāman? stable))
  (1024 (en string? stable) (uk текст? stable) (ukr текст? stable) (sa śabda? stable))
  (1025 (en string<? stable) (uk текст-передує? stable) (ukr текст-передує? stable) (sa śabda-hīna? candidate))
  (1026 (en numeric-buffer? stable) (uk числовий-буфер? stable) (ukr числовий-буфер? stable) (sa — missing))
  (1027 (en list stable) (uk список stable) (ukr список stable) (sa śreṇī stable))
  (1028 (en length stable) (uk довжина stable) (ukr довжина stable) (sa pramāṇa stable))
  (1029 (en append stable) (uk приєднати stable) (ukr приєднати stable) (sa saṅkalana stable))
  (1030 (en reverse stable) (uk зворот stable) (ukr зворот stable) (sa viloma stable))
  (1031 (en nth stable) (uk елемент-списку-за-індексом stable) (ukr елемент-списку-за-індексом stable) (sa kramāṅka stable))
  (1032 (en member? stable) (uk значення-у-списку? stable) (ukr значення-у-списку? stable) (sa sambaddha? candidate))
  (1033 (en assoc stable) (uk знайти-за-ключем stable) (ukr знайти-за-ключем stable) (sa saṃbandha stable))
  (1034 (en pair stable) (uk пара stable) (ukr пара stable) (sa dvandva stable))
  (1035 (en second stable) (uk друге stable) (ukr друге stable) (sa dvitīya stable))
  (1036 (en third stable) (uk третє stable) (ukr третє stable) (sa tṛtīya stable))
  (1037 (en fourth stable) (uk четверте stable) (ukr четверте stable) (sa caturtha stable))
  (1038 (en fifth stable) (uk п'яте stable) (ukr п'яте stable) (sa pañcama stable))
  (1039 (en caar compatibility-only) (uk — compatibility-only) (ukr перше-від-першого candidate) (sa — compatibility-only))
  (1040 (en cadr compatibility-only) (uk — compatibility-only) (ukr перше-від-решти candidate) (sa — compatibility-only))
  (1041 (en cddr compatibility-only) (uk — compatibility-only) (ukr решта-від-решти candidate) (sa — compatibility-only))
  (1042 (en cadddr compatibility-only) (uk — compatibility-only) (ukr перше-після-трьох-решт candidate) (sa — compatibility-only))
  (0101 (en map stable) (uk відобразити stable) (ukr відобразити stable) (sa āvartana candidate))
  (0102 (en filter stable) (uk відсіяти stable) (ukr відсіяти stable) (sa kalpana candidate))
  (0103 (en reduce stable) (uk згорнути stable) (ukr згорнути stable) (sa saṅgraha candidate))
  (1043 (en string-append stable) (uk зчепити stable) (ukr зчепити stable) (sa śabdasaṃyoga candidate))
  (1044 (en string-length stable) (uk довжина-тексту stable) (ukr довжина-тексту stable) (sa śabdapramāṇa candidate))
  (1045 (en string-empty? stable) (uk текст-порожній? stable) (ukr порожній-текст? stable) (sa śūnya? stable))
  (1046 (en string-prefix? stable) (uk префікс-тексту? stable) (ukr текст-починається-з? candidate) (sa pūrva? candidate))
  (1047 (en string-contains? stable) (uk фрагмент-у-тексті? stable) (ukr фрагмент-у-тексті? stable) (sa śabdasambaddha? candidate))
  (1048 (en string-first stable) (uk перший-символ-тексту stable) (ukr перший-символ-тексту stable) (sa prathamavarṇa candidate))
  (1049 (en string-rest stable) (uk решта-символів-тексту stable) (ukr решта-символів-тексту stable) (sa śeṣavarṇa candidate))
  (1050 (en string-slice stable) (uk відрізати stable) (ukr відрізати stable) (sa cheda candidate))
  (1051 (en symbol->string stable) (uk символ-у-текст stable) (ukr символ-у-текст stable) (sa nāman-śabda candidate))
  (1052 (en string->symbol stable) (uk текст-у-символ stable) (ukr текст-у-символ stable) (sa śabda-nāman candidate))
  (1053 (en codepoint->string stable) (uk кодова-точка-у-текст stable) (ukr кодова-точка-у-текст stable) (sa varṇa-śabda candidate))
  (1054 (en string->codepoint stable) (uk текст-у-кодову-точку stable) (ukr текст-у-кодову-точку stable) (sa śabda-varṇa candidate))
  (1055 (en number->string stable) (uk число-у-текст stable) (ukr число-у-текст stable) (sa saṅkhyā-śabda candidate))
  (1056 (en digit->string compatibility-only) (uk — compatibility-only) (ukr цифра-у-текст candidate) (sa — compatibility-only))
  (1057 (en print stable) (uk друкувати stable) (ukr друкувати stable) (sa mudraṇa candidate))
  (1058 (en princ stable) (uk показати stable) (ukr показати stable) (sa darśana candidate))
  (1059 (en read stable) (uk прочитати stable) (ukr прочитати stable) (sa pāṭhana candidate))
  (1060 (en read-all stable) (uk прочитати-усе stable) (ukr прочитати-усе stable) (sa pāṭhana-sarva candidate))
  (1061 (en write-to-string stable) (uk значення-у-текст stable) (ukr значення-у-текст stable) (sa likhana candidate))
  (1062 (en eval stable) (uk обчислити stable) (ukr обчислити stable) (sa vicāraṇa candidate))
  (1063 (en env stable) (uk середовище stable) (ukr середовище stable) (sa āśraya candidate))
  (1064 (en vector stable) (uk вектор stable) (ukr вектор stable) (sa samūha candidate))
  (1065 (en make-vector stable) (uk створити-вектор stable) (ukr створити-вектор stable) (sa samūha-nirmāṇa candidate))
  (1066 (en vector-length stable) (uk довжина-вектора stable) (ukr довжина-вектора stable) (sa samūha-pramāṇa candidate))
  (1067 (en vector-ref stable) (uk елемент-вектора stable) (ukr елемент-вектора stable) (sa samūha-āvartana candidate))
  (1068 (en vector-set! stable) (uk встановити-елемент-вектора! stable) (ukr встановити-елемент-вектора! stable) (sa — missing))
  (1069 (en i32-buffer compatibility-only) (uk — compatibility-only) (ukr буфер-32-бітних-цілих-зі-знаком candidate) (sa — compatibility-only))
  (1070 (en f32-buffer compatibility-only) (uk — compatibility-only) (ukr буфер-32-бітних-чисел-з-плавною-комою candidate) (sa — compatibility-only))
  (1071 (en numeric-buffer-type compatibility-only) (uk — compatibility-only) (ukr тип-числового-буфера candidate) (sa — compatibility-only))
  (1072 (en numeric-buffer-length compatibility-only) (uk — compatibility-only) (ukr довжина-числового-буфера candidate) (sa — compatibility-only))
  (1073 (en numeric-buffer-ref compatibility-only) (uk — compatibility-only) (ukr елемент-числового-буфера candidate) (sa — compatibility-only))
  (1074 (en numeric-buffer-map compatibility-only) (uk — compatibility-only) (ukr відобразити-числовий-буфер candidate) (sa — compatibility-only))
  (1075 (en mono-ns stable) (uk монотонний-нс stable) (ukr монотонний-час-у-наносекундах candidate) (sa kāla-mono candidate))
  (1076 (en unix-time-now stable) (uk поточний-юнікс-час stable) (ukr поточний-юнікс-час stable) (sa kāla-unix candidate))
  (1077 (en ntp-query-raw compatibility-only) (uk — compatibility-only) (ukr сирий-запит-мережевого-часу candidate) (sa — compatibility-only))
  (1078 (en timezone-declarations-raw compatibility-only) (uk — compatibility-only) (ukr сирі-декларації-часових-поясів candidate) (sa — compatibility-only))
  (1079 (en utc-now stable) (uk поточний-всч stable) (ukr поточний-всесвітній-координований-час candidate) (sa kāla-adya candidate))
  (1080 (en utc-from-unix stable) (uk всч-із-юнікс stable) (ukr всесвітній-координований-час-із-часу-юнікс candidate) (sa — missing))
  (1081 (en unix-time-observation->utc stable) (uk юнікс-спостереження-у-всч stable) (ukr спостереження-часу-юнікс-у-всесвітній-координований-час candidate) (sa — missing))
  (1082 (en milliseconds-from-nanoseconds stable) (uk мілісекунди-із-наносекунд stable) (ukr мілісекунди-із-наносекунд stable) (sa kāla-millisecondāni candidate))
  (1083 (en mono-ms stable) (uk монотонний-мс stable) (ukr монотонний-час-у-мілісекундах candidate) (sa kāla-mono-ms candidate))
  (1084 (en timezone-name stable) (uk назва-часового-поясу stable) (ukr назва-часового-поясу stable) (sa deśa-kāla-nāma candidate))
  (1085 (en timezone-detect stable) (uk визначити-часовий-пояс stable) (ukr визначити-часовий-пояс stable) (sa deśa-kāla-jñāna candidate))
  (1086 (en timezone-offset-seconds stable) (uk зміщення-часового-поясу-в-секундах stable) (ukr зміщення-часового-поясу-в-секундах stable) (sa deśa-kāla-śeṣa candidate))
  (1087 (en deadline-reached? stable) (uk дедлайн-досягнуто? stable) (ukr граничний-час-досягнуто? candidate) (sa avadhi-gatā? candidate))
  (1088 (en deadline-reached-at? stable) (uk дедлайн-досягнуто-на-момент? stable) (ukr граничний-час-досягнуто-на-момент? candidate) (sa avadhi-gatā-kadā? candidate))
  (1089 (en elapsed-ns stable) (uk минуло-нс stable) (ukr минуло-наносекунд candidate) (sa atīta-ns candidate))
  (1090 (en deadline-from stable) (uk дедлайн-від stable) (ukr граничний-час-від candidate) (sa avadhi-nirmāṇa candidate))
  (1091 (en deadline-after-ns stable) (uk дедлайн-через-нс stable) (ukr граничний-час-через-наносекунди candidate) (sa avadhi-anantara-ns candidate))
  (1092 (en internet-time-sync stable) (uk запитати-інтернет-час stable) (ukr синхронізувати-час-через-інтернет candidate) (sa — missing))
  (1093 (en map-empty stable) (uk порожня-карта stable) (ukr порожня-карта stable) (sa kośa-śūnya candidate))
  (1094 (en map-get stable) (uk отримати-з-карти stable) (ukr отримати-з-карти stable) (sa kośa-grahaṇa candidate))
  (1095 (en map-insert stable) (uk вставити-в-карту stable) (ukr вставити-в-карту stable) (sa kośa-niveśana candidate))
  (1096 (en map-contains? stable) (uk ключ-у-карті? stable) (ukr ключ-у-карті? stable) (sa kośa-sambaddha? candidate))
  (1097 (en map->list stable) (uk карта-у-список stable) (ukr карта-у-список stable) (sa kośa-śreṇī candidate))
  (1098 (en vec-empty stable) (uk порожній-вектор stable) (ukr порожній-вектор stable) (sa samūha-śūnya candidate))
  (1099 (en vec-conj stable) (uk додати-до-вектора stable) (ukr додати-до-вектора stable) (sa samūha-yukti candidate))
  (1100 (en vec-count stable) (uk розмір-вектора stable) (ukr розмір-вектора stable) (sa samūha-gaṇana candidate))
  (1101 (en vec-nth stable) (uk елемент-вектора-за-індексом stable) (ukr елемент-вектора-за-індексом stable) (sa samūha-kramāṅka candidate))
  (1102 (en vec->list stable) (uk вектор-у-список stable) (ukr вектор-у-список stable) (sa samūha-śreṇī candidate))
  (1103 (en vec-from-list stable) (uk вектор-із-списку stable) (ukr вектор-із-списку stable) (sa śreṇī-samūha candidate))
  (1104 (en is-fact? stable) (uk факт? stable) (ukr факт? stable) (sa jñāna-satya? candidate))
  (1105 (en describe stable) (uk описати stable) (ukr описати stable) (sa varṇana candidate))
  (1106 (en collect-facts-about stable) (uk зібрати-факти-про stable) (ukr зібрати-факти-про stable) (sa jñāna-saṅgraha candidate))
  (1107 (en contains-atom? stable) (uk атом-у-списку? stable) (ukr атом-у-списку? stable) (sa aṇu-sambaddha? candidate))
  (1108 (en forward-in stable) (uk пряме-виведення stable) (ukr пряме-виведення stable) (sa abhimukha-anumāna candidate))
  (1109 (en reason-in stable) (uk логічний-висновок stable) (ukr логічний-висновок stable) (sa anumāna candidate))
  (1110 (en check-conflict stable) (uk конфлікт? stable) (ukr є-конфлікт? candidate) (sa virodha-parīkṣā candidate))
  (1111 (en module-known? stable) (uk модуль-відомий? stable) (ukr модуль-відомий? stable) (sa — missing))
  (1112 (en module-clauses-now stable) (uk поточні-клаузи-модуля stable) (ukr поточні-клаузи-модуля stable) (sa — missing))
  (1113 (en prove-goal stable) (uk довести-мету stable) (ukr довести-мету stable) (sa siddhi-sādhana candidate))
  (1114 (en prove-goals stable) (uk довести-мети stable) (ukr довести-мети stable) (sa siddhi-sādhana-sarva candidate))
  (1115 (en explain-proof stable) (uk пояснити-доведення stable) (ukr пояснити-доведення stable) (sa siddhi-vyākhyā candidate))
  (1116 (en source-of stable) (uk джерело-доведення stable) (ukr джерело-доведення stable) (sa siddhi-mūla candidate))
  (1117 (en provenance stable) (uk походження stable) (ukr походження stable) (sa utpatti candidate))
  (1118 (en reason stable) (uk міркування stable) (ukr міркування stable) (sa tarka candidate))
  (1119 (en reason-explain stable) (uk пояснити-міркування stable) (ukr пояснити-міркування stable) (sa tarka-vyākhyā candidate))
  (1120 (en unify stable) (uk уніфікувати stable) (ukr уніфікувати stable) (sa ekīkaraṇa candidate))
  (1121 (en logic-var stable) (uk логічна-змінна stable) (ukr логічна-змінна stable) (sa tarka-cihna candidate))
  (1122 (en var? stable) (uk змінна? stable) (ukr змінна? stable) (sa cihna? candidate))
  (1123 (en apply-subst stable) (uk підставити stable) (ukr підставити stable) (sa pratyāroha candidate))
  (1124 (en walk stable) (uk розіменувати stable) (ukr розіменувати stable) (sa vicāraṇa-gamana candidate))
  (1125 (en occurs-check stable) (uk змінна-зустрічається? stable) (ukr змінна-зустрічається? stable) (sa parivṛtti-parīkṣā candidate))
  (1126 (en claim? stable) (uk твердження? stable) (ukr твердження? stable) (sa pratyaya? candidate))
  (1127 (en claim-statement stable) (uk зміст-твердження stable) (ukr зміст-твердження stable) (sa pratyaya-vākya candidate))
  (1128 (en claim-review stable) (uk стан-розгляду-твердження stable) (ukr стан-розгляду-твердження stable) (sa pratyaya-parīkṣā candidate))
  (1129 (en evidence? stable) (uk доказ? stable) (ukr доказ? stable) (sa pramāṇa? candidate))
  (1130 (en evidence-method stable) (uk метод-доказу stable) (ukr метод-доказу stable) (sa pramāṇa-vidhi candidate))
  (1131 (en evidence-outcome stable) (uk результат-доказу stable) (ukr результат-доказу stable) (sa pramāṇa-phala candidate))
  (1132 (en observation? stable) (uk спостереження? stable) (ukr спостереження? stable) (sa pratyakṣa? candidate))
  (1133 (en observation-statement stable) (uk зміст-спостереження stable) (ukr зміст-спостереження stable) (sa pratyakṣa-vākya candidate))
  (1134 (en intent? stable) (uk намір? stable) (ukr намір? stable) (sa saṅkalpa? candidate))
  (1135 (en intent-goal stable) (uk мета-наміру stable) (ukr мета-наміру stable) (sa saṅkalpa-lakṣya candidate))
  (1136 (en supporting-evidence stable) (uk підтримувальний-доказ stable) (ukr підтримувальний-доказ stable) (sa sahāya-pramāṇa candidate))
  (1137 (en identity stable) (uk без-змін stable) (ukr повернути-без-змін candidate) (sa svabhāva candidate))
  (1138 (en gensym stable) (uk генерувати-символ stable) (ukr створити-унікальний-символ candidate) (sa nāman-nirmāṇa candidate))
  (1139 (en and stable) (uk та stable) (ukr та stable) (sa — missing))
  (1140 (en or stable) (uk або stable) (ukr або stable) (sa — missing))
  (1141 (en let stable) (uk нехай stable) (ukr нехай stable) (sa — missing))
  (1142 (en let* stable) (uk нехай* stable) (ukr нехай-послідовно candidate) (sa — missing))
  (1143 (en — compatibility-only) (uk — compatibility-only) (ukr ланцюжок-першого-аргументу candidate) (sa — compatibility-only) (sym -> compatibility-only))
  (1144 (en — compatibility-only) (uk — compatibility-only) (ukr ланцюжок-останнього-аргументу candidate) (sa — compatibility-only) (sym ->> compatibility-only))
  (1145 (en json-parse compatibility-only) (uk — compatibility-only) (ukr розібрати-текст-формату-джейсон candidate) (sa — compatibility-only))
  (1146 (en sha256-hex compatibility-only) (uk — compatibility-only) (ukr обчислити-хеш-ша-256-тексту-у-шістнадцятковому-записі candidate) (sa — compatibility-only))
  (1147 (en process-run stable) (uk запустити-процес candidate) (ukr запустити-процес candidate) (sa — missing))
  (1148 (en tcp-read stable) (uk прочитати-текст-з-з'єднання-протоколу-керування-передаванням candidate) (ukr прочитати-текст-з-з'єднання-протоколу-керування-передаванням candidate) (sa — missing))
  (1149 (en tcp-write stable) (uk записати-текст-у-з'єднання-протоколу-керування-передаванням candidate) (ukr записати-текст-у-з'єднання-протоколу-керування-передаванням candidate) (sa — missing))
  (1150 (en tcp-listen stable) (uk слухати-порт-протоколу-керування-передаванням candidate) (ukr слухати-порт-протоколу-керування-передаванням candidate) (sa — missing))
  (1151 (en read-file stable) (uk прочитати-файл candidate) (ukr прочитати-файл candidate) (sa — missing))
  (1152 (en write-file stable) (uk записати-файл candidate) (ukr записати-файл candidate) (sa — missing))
)
